---
# tasks file for volume

- name: Install volume control script
  become: yes
  ansible.builtin.template:
    src: volume.sh.j2
    dest: "/usr/local/bin/volume.sh"
    mode: '0755'
  notify: restart volume service

- name: Generate volume system service
  become: yes
  ansible.builtin.template:
    src: volume.service.j2
    dest: /etc/systemd/system/volume.service
    mode: '0644'
  notify: 
    - reload systemd daemon
    - restart volume service

- name: Enable and start volume system service
  become: yes
  ansible.builtin.systemd:
    name: volume.service
    state: started
    enabled: yes