---
# tasks file for volume

- name: Install volume control script
  become: yes
  ansible.builtin.template:
    src: volume.sh.j2
    dest: "{{ SYSTEM_BIN_DIR }}/volume.sh"
    mode: '0755'

- name: Ensure user systemd directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/systemd/user"
    state: directory
    mode: '0755'
  become: no

- name: Generate systemd user service for volume
  ansible.builtin.template:
    src: volume.service.j2
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/volume.service"
    mode: '0644'
  become: no
  notify: restart volume service

- name: Enable and start volume user service
  ansible.builtin.systemd:
    name: volume.service
    state: started
    enabled: yes
    scope: user
    daemon_reload: yes
  become: no
