---
# Generate a pseudo-random MAC address based on inventory_hostname for idempotency across all roles
player_mac: "02:{{ '%02x:%02x:%02x:%02x:%02x' | format(255 | random(seed=inventory_hostname), 255 | random(seed=inventory_hostname + '1'), 255 | random(seed=inventory_hostname + '2'), 255 | random(seed=inventory_hostname + '3'), 255 | random(seed=inventory_hostname + '4')) }}"

# Global LMS Server configuration
lms_server_ip: "192.168.50.210"
lms_server_port: "9000"