---
- name: Enable user Linger mode (Required for user systemd services)
  become: yes
  ansible.builtin.command: "loginctl enable-linger {{ ansible_user_id }}"
  changed_when: false

- name: Set system timezone
  become: yes
  ansible.builtin.command: "timedatectl set-timezone {{ system_timezone | default('America/Vancouver') }}"
  changed_when: false

- name: Ensure en_GB.UTF-8 locale is enabled
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/locale.gen
    regexp: '^#?\s*en_GB\.UTF-8\s+UTF-8'
    line: 'en_GB.UTF-8 UTF-8'
  register: locale_gen

- name: Generate locales
  become: yes
  ansible.builtin.command: locale-gen
  when: locale_gen.changed

- name: Add bash alias ll='ls -l'
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "alias ll='ls -l'"
    state: present
  become: no