---
- name: Setup Raspberry Pi Media Player
  hosts: all
  become: yes

  roles:
    - role: system
    - role: pipewire
    - role: volume
    - role: squeezelite
    - role: oled
    - role: airplay
    - role: bluetooth
